from setuptools import setup, find_packages
setup(
    name = "django-native-datatables",
    version = "0.8.1",
    packages = find_packages(),
    author = "Christopher Keele",
    author_email = "email@chriskeele.com",
    description = "Add high-performance data-driven tables to your models, with full control template-side",
    long_description = open('README.txt').read(),
    url = "",
    include_package_data = True,
    zip_safe = False,
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Intended Audience :: Developers',
        'Operating System :: OS Independent',
        'Programming Language :: JavaScript',
        'Programming Language :: Python',
        'Topic :: Software Development :: Libraries :: Application Frameworks',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Database :: Front-Ends',
    ],
)